import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const appRoot = resolve(__dirname, '..');

const pkg = JSON.parse(readFileSync(resolve(appRoot, 'package.json'), 'utf-8')) as { version: string; name: string };

const version = pkg.version ?? '0.0.0';
const appName = pkg.name ?? 'app';
const buildTime = new Date().toISOString();

const content = `// This file is auto-generated by appMetadataGenerator.ts — do not edit manually.
// It is regenerated on every build.

const APP_INFO = {
  appName: '${appName}',
  version: '${version}',
  buildTime: '${buildTime}',
} as const;

export default APP_INFO;
`;

const outPath = resolve(appRoot, 'src', 'app-info.ts');
writeFileSync(outPath, content, 'utf-8');
console.log(`[appMetadataGenerator] Generated src/app-info.ts  v${version}  built ${buildTime}`);
